### ISSUE TITLE
GEOID difference

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/open-data-pipeline#35]
What is the difference between GEOID left and GEOID right in the chicago death data?

**Comment by nanthony007** [comment]
This is likely the result of joining so left would be the left table right the right table whenever I did a join. Are those columns data identical? If so you can just pick one for now and forget the other. I will remove them eventually. This happens when you join two tables with the same column names.

**Comment by cdelcher** [comment]
They have different census tract numbers so that’s why I’m confused as to the true representation of the incident location.
Chris Delcher, PhD

On May 21, 2024, at 12:56 PM, Nick Anthony ***@***.***> wrote:

﻿
CAUTION: External Sender


This is likely the result of joining so left would be the left table right the right table whenever I did a join. Are those columns data identical? If so you can just pick one for now and forget the other. I will remove them eventually. This happens when you join two tables with the same column names.

**Comment by nanthony007** [comment]
Resolved as of #44
